apiVersion: 1

groups:
    - orgId: 1
      name: IOT-evaluation-group
      folder: IOT-alerts
      interval: 1m
      rules:
        - uid: d83ec0e8-d7c5-42dc-8290-96c00e247b6d
          title: No data or below zero value in IOT sensors
          condition: C
          data:
            - refId: D
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: influxdb
              model:
                datasource:
                    type: influxdb
                    uid: influxdb
                groupBy:
                    - params:
                        - friendly_name::tag
                      type: tag
                    - params:
                        - "0"
                      type: fill
                intervalMs: 1000
                maxDataPoints: 43200
                measurement: prometheus
                orderByTime: ASC
                policy: default
                query: "from(bucket: \"influx/autogen\")\r\n  |> range(start: -1m)\r\n  |> last()\r\n  |> filter(fn: (r) => r._field != \"start_time_unix_nano\")"
                rawQuery: false
                refId: D
                resultFormat: time_series
                select:
                    - - params:
                            - '*'
                        type: field
                      - params: []
                        type: last
                tags:
                    - key: state_class::tag
                      operator: =
                      value: measurement
            - refId: B
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: D
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                settings:
                    mode: ""
                type: reduce
            - refId: C
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - -1e+28
                            - 100
                        type: lt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: B
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: Alerting
          execErrState: Alerting
          for: 1m
          annotations:
            description: ""
            runbook_url: ""
            summary: ""
          labels:
            "": ""
            type: iot
          isPaused: false
    - orgId: 1
      name: IOT-airquality
      folder: IOT-alerts
      interval: 1m
      rules:
        - uid: e1cf45ec-eee7-4346-bdc6-5139b279cd95
          title: Bad air quality in IOT sensors
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: influxdb
              model:
                intervalMs: 1000
                maxDataPoints: 43200
                query: "from(bucket: \"influx/autogen\")\r\n  |> range(start: -1m)\r\n  |> last()\r\n  |> filter(fn: (r) => r._field != \"start_time_unix_nano\" and r[\"unit_of_measurement\"] == \"µg/m³\")"
                refId: A
            - refId: B
              datasourceUid: __expr__
              model:
                conditions:
                  - evaluator:
                      params:
                        - 0
                        - 0
                      type: gt
                    operator:
                      type: and
                    query:
                      params: []
                    reducer:
                      params: []
                      type: avg
                    type: query
                datasource:
                  name: Expression
                  type: __expr__
                  uid: __expr__
                expression: A
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                  - evaluator:
                      params:
                        - 20
                        - 0
                      type: gt
                    operator:
                      type: and
                    query:
                      params: []
                    reducer:
                      params: []
                      type: avg
                    type: query
                datasource:
                  name: Expression
                  type: __expr__
                  uid: __expr__
                expression: B
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: Alerting
          execErrState: Alerting
          for: 1m
          annotations: {}
          labels:
            type: iot
          isPaused: false
    - orgId: 1
      name: IOT-water-leakage
      folder: IOT-alerts
      interval: 1m
      rules:
        - uid: aechmlhqyxqtcd
          title: Water leakage in IOT sensors
          condition: B
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: influxdb
              model:
                intervalMs: 1000
                maxDataPoints: 43200
                query: "from(bucket: \"influx/autogen\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r._field != \"start_time_unix_nano\" and r.device_class == \"moisture\" and r.state_class != \"measurement\")\r\n|> group(columns: [\"_field\"])\r\n|> last()\r\n|> keep(columns: [\"friendly_name\", \"_value\"])"
                refId: A
            - refId: B
              datasourceUid: __expr__
              model:
                conditions:
                  - evaluator:
                      params:
                        - 0
                        - 0
                      type: gt
                    operator:
                      type: and
                    query:
                      params: []
                    reducer:
                      params: []
                      type: avg
                    type: query
                datasource:
                  name: Expression
                  type: __expr__
                  uid: __expr__
                expression: A
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                refId: B
                type: threshold
          noDataState: Alerting
          execErrState: Alerting
          for: 1m
          labels:
            type: iot
          isPaused: false
    - orgId: 1
      name: IOT-battery
      folder: IOT-alerts
      interval: 1m
      rules:
        - uid: cechpy40xhq80a
          title: Low battery in IOT sensors
          condition: B
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: influxdb
              model:
                intervalMs: 1000
                maxDataPoints: 43200
                query: "from(bucket: \"influx/autogen\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r._field != \"start_time_unix_nano\" and r.device_class == \"battery\")\r\n|> group(columns: [\"_field\"])\r\n|> last()\r\n|> keep(columns: [\"friendly_name\", \"_value\"])\r\n|> sort(columns: [\"_value\"], desc: false)"
                refId: A
            - refId: B
              datasourceUid: __expr__
              model:
                conditions:
                  - evaluator:
                      params:
                        - 30
                        - 0
                      type: lt
                    operator:
                      type: and
                    query:
                      params: []
                    reducer:
                      params: []
                      type: avg
                    type: query
                datasource:
                  name: Expression
                  type: __expr__
                  uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: B
                type: threshold
          noDataState: Alerting
          execErrState: Alerting
          for: 1m
          labels:
            type: iot
          isPaused: false
    - orgId: 1
      name: IOT-soil-moisture
      folder: IOT-alerts
      interval: 1m
      rules:
        - uid: feci6h3c0c0zkb
          title: Low soil moisture in IOT sensors
          condition: B
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: influxdb
              model:
                intervalMs: 1000
                maxDataPoints: 43200
                query: "from(bucket: \"influx/autogen\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r._field != \"start_time_unix_nano\" and r.device_class == \"moisture\" and r.state_class == \"measurement\" and r._value != -1)\r\n|> group(columns: [\"_field\"])\r\n|> last()\r\n|> keep(columns: [\"friendly_name\", \"_value\"])"
                refId: A
            - refId: B
              datasourceUid: __expr__
              model:
                conditions:
                  - evaluator:
                      params:
                        - 60
                        - 0
                      type: lt
                    operator:
                      type: and
                    query:
                      params: []
                    reducer:
                      params: []
                      type: avg
                    type: query
                datasource:
                  name: Expression
                  type: __expr__
                  uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: B
                type: threshold
          noDataState: Alerting
          execErrState: Alerting
          for: 1m
          labels:
            type: iot
          isPaused: false