apiVersion: 1

contactPoints:
    - orgId: 1
      name: grafana-default-email
      receivers:
        - uid: e127d87b-4886-461e-a8ee-dcf8fde6a873
          type: email
          settings:
            addresses: <youremail@email.com>
            singleEmail: false
          disableResolveMessage: false
