version: '3.6'

services:
  influxdb:
    image: influxdb:1.8-alpine
    restart: always
    environment:
      - INFLUXDB_DB=influx
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=secrettoken
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb
      - ./influx:/etc/influxdb

  grafana:
    image: grafana/grafana
    restart: always
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=
    links:
      - influxdb
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/alerting:/etc/grafana/provisioning/alerting

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.84.0
    restart: always
    depends_on:
      - influxdb
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4318:4318"   # OTLP gRPC receiver

volumes:
  grafana_data: {}
  influxdb_data: {}