receivers:
  otlp:
    protocols:
      http:

exporters:
  influxdb:
    endpoint: http://influxdb:8086
    bucket: influx
    token: secrettoken
    metrics_schema: telegraf-prometheus-v2
  prometheus:
    endpoint: "0.0.0.0:1234"
    namespace: ha-sensors
    send_timestamps: true
    metric_expiration: 180m
    resource_to_telemetry_conversion:
      enabled: true

service:
  telemetry:
    logs:
      level: debug
      encoding: json

  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [influxdb, prometheus]