{
 "title": "IOT",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Humidity sensors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "measurement": "prometheus",
     "query": "from(bucket: \"influx/autogen\")\r\n  |> range(start: -30m)\r\n  |> filter(fn: (r) => r._field != \"start_time_unix_nano\" and r.device_class == \"humidity\")",
     "select": [
      [
       {
        "params": [
         "sensor.ikea_of_sweden_vindstyrka_humidity"
        ],
        "type": "field"
       }
      ],
      [
       {
        "params": [
         "sensor.sonoff_temperature_sensor_humidity"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature sensors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "measurement": "prometheus",
     "query": "from(bucket: \"influx/autogen\")\r\n  |> range(start: -30m)\r\n  |> filter(fn: (r) => r._field != \"start_time_unix_nano\" and r.device_class == \"temperature\")",
     "select": [
      [
       {
        "params": [
         "sensor.ikea_of_sweden_vindstyrka_humidity"
        ],
        "type": "field"
       }
      ],
      [
       {
        "params": [
         "sensor.sonoff_temperature_sensor_humidity"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Other sensors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "measurement": "prometheus",
     "query": "from(bucket: \"influx/autogen\")\r\n  |> range(start: -30m)\r\n  |> filter(fn: (r) => r._field != \"start_time_unix_nano\" and not exists r.device_class)",
     "select": [
      [
       {
        "params": [
         "sensor.ikea_of_sweden_vindstyrka_humidity"
        ],
        "type": "field"
       }
      ],
      [
       {
        "params": [
         "sensor.sonoff_temperature_sensor_humidity"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  }
 ]
}