{
 "title": "IOT (v2)",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Temperature sensors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"influx/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field != \"start_time_unix_nano\" and r.device_class == \"temperature\")"
    }
   ]
  },
  {
   "title": "Humidity sensors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"influx/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field != \"start_time_unix_nano\" and r.device_class == \"humidity\")"
    }
   ]
  },
  {
   "title": "Temperature sensors",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"influx/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field != \"start_time_unix_nano\" and r.device_class == \"temperature\")"
    }
   ]
  },
  {
   "title": "Humidity sensors",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"influx/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field != \"start_time_unix_nano\" and r.device_class == \"humidity\")"
    }
   ]
  },
  {
   "title": "Air Quality",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"influx/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field != \"start_time_unix_nano\" and r.unit_of_measurement == \"µg/m³\")"
    }
   ]
  },
  {
   "title": "Air Quality",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 19, "x": 5, "y": 12 },
   "targets": [
    {
     "query": "from(bucket: \"influx/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field != \"start_time_unix_nano\" and r.unit_of_measurement == \"µg/m³\")"
    }
   ]
  },
  {
   "title": "Soil Moisture",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"influx/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field != \"start_time_unix_nano\" and r.device_class == \"moisture\")"
    }
   ]
  },
  {
   "title": "Battery",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 19, "x": 5, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: \"influx/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field != \"start_time_unix_nano\" and r.device_class == \"battery\")"
    }
   ]
  }
 ]
}