apiVersion: 1

datasources:
  - name: InfluxDB_v1
    type: influxdb
    access: proxy
    user: admin
    url: http://influxdb:8086
    jsonData:
      dbName: influx
      httpMode: GET
    secureJsonData:
      password: admin