apiVersion: 1

datasources:
  - name: InfluxDB-Flux
    type: influxdb
    uid: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: iot
      defaultBucket: autogen
      tlsSkipVerify: true
    secureJsonData:
      token: secrettoken